#!/usr/bin/env bash
BOOK=${1?"missing book name ..."}
BIBLE=https://zh.m.wikisource.org/wiki/聖經_\(和合本\)
BOOKLINK=$BIBLE/$BOOK
GETBWSK=$HOME/bible2zhtts/getbwsk.js
GETLINK=$HOME/bible2zhtts/getlinks.js
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
$GETBWSK $BOOKLINK | grep ^[第0123456789] > converted.txt
../prepare_coverparameters
../mov_with
../mk_text_subdir 
#~/move2zhtts 
