#!/usr/bin/env bash
BOOK=${1?"missing book name ..."}
BOOKLINK=${2?"missing link of book name ..."}
#JAWIKI=https://ja.wikisource.org/wiki
JAWIKI=https://zh.m.wikisource.org/wiki
#https://zh.m.wikisource.org/wiki/聖經_(和合本)
GETBWSK=$HOME/jafiction2wspa/getbwsk.js
GETLINK=$HOME/jafiction2wspa/getlinks.js
[ -d $BOOK ] || mkdir $BOOK
cd $BOOK
$GETLINK $BOOKLINK | $DECODEURI > link.txt
$GETBWSK $BOOKLINK | sed -e 's#\.mw-par.*\}##g' -e '/^Public domain/,$ d' > converted.txt
