./zh_bible_ws 創世記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/創世記
./zh_bible_ws 出埃及記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/出埃及記
./zh_bible_ws 利未記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/利未記
./zh_bible_ws 民數記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/民數記
./zh_bible_ws 申命記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/申命記
./zh_bible_ws 約書亞記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約書亞記
./zh_bible_ws 士師記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/士師記
./zh_bible_ws 路得記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/路得記
./zh_bible_ws 撒母耳記上 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/撒母耳記上
./zh_bible_ws 撒母耳記下 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/撒母耳記下
./zh_bible_ws 列王紀上 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/列王紀上
./zh_bible_ws 列王紀下 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/列王紀下
./zh_bible_ws 歷代志上 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/歷代志上
./zh_bible_ws 歷代志下 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/歷代志下
./zh_bible_ws 以斯拉記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/以斯拉記
./zh_bible_ws 尼希米記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/尼希米記
./zh_bible_ws 以斯帖記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/以斯帖記
./zh_bible_ws 約伯記 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約伯記
./zh_bible_ws 詩篇 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/詩篇
./zh_bible_ws 箴言 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/箴言
./zh_bible_ws 傳道書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/傳道書
./zh_bible_ws 雅歌 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/雅歌
./zh_bible_ws 以賽亞書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/以賽亞書
./zh_bible_ws 耶利米書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/耶利米書
./zh_bible_ws 耶利米哀歌 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/耶利米哀歌
./zh_bible_ws 以西結書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/以西結書
./zh_bible_ws 但以理書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/但以理書
./zh_bible_ws 何西阿書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/何西阿書
./zh_bible_ws 約珥書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約珥書
./zh_bible_ws 阿摩司書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/阿摩司書
./zh_bible_ws 俄巴底亞書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/俄巴底亞書
./zh_bible_ws 約拿書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約拿書
./zh_bible_ws 彌迦書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/彌迦書
./zh_bible_ws 那鴻書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/那鴻書
./zh_bible_ws 哈巴谷書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/哈巴谷書
./zh_bible_ws 西番雅書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/西番雅書
./zh_bible_ws 哈該書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/哈該書
./zh_bible_ws 撒迦利亞書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/撒迦利亞書
./zh_bible_ws 瑪拉基書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/瑪拉基書
./zh_bible_ws 馬太福音 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/馬太福音
./zh_bible_ws 馬可福音 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/馬可福音
./zh_bible_ws 路加福音 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/路加福音
./zh_bible_ws 約翰福音 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約翰福音
./zh_bible_ws 使徒行傳 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/使徒行傳
./zh_bible_ws 羅馬書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/羅馬書
./zh_bible_ws 哥林多前書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/哥林多前書
./zh_bible_ws 哥林多後書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/哥林多後書
./zh_bible_ws 加拉太書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/加拉太書
./zh_bible_ws 以弗所書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/以弗所書
./zh_bible_ws 腓立比書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/腓立比書
./zh_bible_ws 歌羅西書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/歌羅西書
./zh_bible_ws 帖撒羅尼迦前書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/帖撒羅尼迦前書
./zh_bible_ws 帖撒羅尼迦後書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/帖撒羅尼迦後書
./zh_bible_ws 提摩太前書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/提摩太前書
./zh_bible_ws 提摩太後書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/提摩太後書
./zh_bible_ws 提多書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/提多書
./zh_bible_ws 腓利門書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/腓利門書
./zh_bible_ws 希伯來書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/希伯來書
./zh_bible_ws 雅各書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/雅各書
./zh_bible_ws 彼得前書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/彼得前書
./zh_bible_ws 彼得後書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/彼得後書
./zh_bible_ws 約翰一書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約翰一書
./zh_bible_ws 約翰二書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約翰二書
./zh_bible_ws 約翰三書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/約翰三書
./zh_bible_ws 猶大書 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/猶大書
./zh_bible_ws 啟示錄 https://zh.m.wikisource.org/wiki/聖經_\(和合本\)/啟示錄
